services:
  hydroxide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proton-mail2
    ports:
      - "1026:1025"
      - "1144:1143"
    volumes:
      # - hydroxide-volume:/data
      - ./data-hydroxide:/data
      # - ./auth-hydroxide:/root/.config/hydroxide
    restart: always
# volumes:
#   hydroxide-volume:
