services:
  hydroxide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proton-mail
    ports:
      - "1025:1025"
      - "1145:1143"
    volumes:
      # - hydroxide-volume:/data
      - ./data-hydroxide:/data
      - ./auth-hydroxide:/root/.config/hydroxide
    restart: always
# volumes:
#   hydroxide-volume:
