services:
  hydroxide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proton-mail
    environment:
      # Set to "true" (or 1/yes/on/debug) to enable Hydroxide debug logs via start.sh
      HYDROXIDE_DEBUG: "${HYDROXIDE_DEBUG:-false}"
    ports:
      - "1025:1025"
      - "1145:1143"
    volumes:
      # - hydroxide-volume:/data
      - ./data-hydroxide:/data
      - ./auth-hydroxide:/root/.config/hydroxide
    restart: always
# volumes:
#   hydroxide-volume:
